# Generated by Django 2.2 on 2019-04-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_icon',
            field=models.BinaryField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='user_nearLogin',
            field=models.SmallIntegerField(default=0),
        ),
    ]
