# Generated by Django 2.2 on 2019-04-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190423_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_icon',
        ),
    ]
