# Generated by Django 2.2 on 2019-04-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_icon',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
