# Generated by Django 2.2 on 2019-04-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_user_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_nearLogin',
        ),
    ]
