# Generated by Django 2.2 on 2019-04-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_grade',
        ),
    ]
