# Generated by Django 2.2 on 2019-04-27 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_student_student_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.SmallIntegerField(default=0)),
                ('order_description', models.CharField(max_length=100)),
                ('order_detail', models.CharField(max_length=100)),
                ('order_bonus', models.IntegerField()),
                ('order_publishDate', models.DateTimeField()),
                ('order_pick', models.SmallIntegerField(default=0)),
                ('order_complish', models.SmallIntegerField(default=0)),
                ('order_complishDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='publishOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='pickOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
