# Generated by Django 2.2 on 2019-04-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190427_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_sex',
            new_name='student_gender',
        ),
    ]
