# Generated by Django 2.2 on 2019-04-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.SmallIntegerField(default=0)),
                ('order_description', models.CharField(max_length=100)),
                ('order_detail', models.CharField(max_length=100)),
                ('order_bonus', models.IntegerField()),
                ('order_publishDate', models.DateTimeField()),
                ('order_picked', models.SmallIntegerField(default=0)),
                ('order_complished', models.SmallIntegerField(default=0)),
                ('order_complishDate', models.DateTimeField()),
            ],
        ),
    ]
