# Generated by Django 2.2 on 2019-05-01 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=11)),
                ('user_password', models.CharField(max_length=20)),
                ('user_icon', models.BinaryField(default=None, null=True)),
                ('user_balance', models.FloatField(default=0.0)),
                ('user_fillln', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.SmallIntegerField(default=0)),
                ('task_sketch', models.CharField(max_length=100)),
                ('task_bonus', models.IntegerField()),
                ('task_publishDate', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.User')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('student_university', models.CharField(max_length=50)),
                ('student_academy', models.CharField(max_length=50)),
                ('student_gender', models.SmallIntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.User')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_closed', models.SmallIntegerField(default=0)),
                ('questionnaire_deadline', models.DateTimeField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.CharField(max_length=100)),
                ('question_type', models.SmallIntegerField(default=0)),
                ('question_a', models.CharField(max_length=100)),
                ('question_b', models.CharField(max_length=100)),
                ('question_c', models.CharField(max_length=100)),
                ('question_d', models.CharField(max_length=100)),
                ('questionnaire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='PublishTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.Task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.User')),
            ],
        ),
        migrations.CreateModel(
            name='PickOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.Task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.User')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_id', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.User')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.User')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_detail', models.CharField(max_length=100)),
                ('delivery_picked', models.SmallIntegerField(default=0)),
                ('delivery_complished', models.SmallIntegerField(default=0)),
                ('delivery_complishDate', models.DateTimeField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.SmallIntegerField(default=0)),
                ('bill_number', models.IntegerField(default=0)),
                ('bill_description', models.CharField(max_length=100)),
                ('bill_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.User')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.Questionnaire')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.User')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.CharField(max_length=100)),
                ('answerSheet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.AnswerSheet')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xianyu.Question')),
            ],
        ),
    ]
