# Generated by Django 2.2 on 2019-05-16 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answerSheet_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('answer_content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('answerSheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('questionnaire_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('bill_type', models.SmallIntegerField(default=0)),
                ('bill_number', models.IntegerField(default=0)),
                ('bill_description', models.CharField(max_length=100)),
                ('bill_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('delivery_detail', models.CharField(max_length=100)),
                ('delivery_picked', models.SmallIntegerField(default=0)),
                ('delivery_complished', models.SmallIntegerField(default=0)),
                ('delivery_complishDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fan_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('following_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PickTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('task_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PublishTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('task_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('questionnaire_id', models.IntegerField()),
                ('question_description', models.CharField(max_length=100)),
                ('question_type', models.SmallIntegerField(default=0)),
                ('question_a', models.CharField(max_length=100)),
                ('question_b', models.CharField(max_length=100)),
                ('question_c', models.CharField(max_length=100)),
                ('question_d', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('questionnaire_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('questionnaire_closed', models.SmallIntegerField(default=0)),
                ('questionnaire_deadline', models.DateTimeField(default=None, null=True)),
                ('questionnaire_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('student_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('student_university', models.CharField(max_length=50)),
                ('student_academy', models.CharField(max_length=50)),
                ('student_gender', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('task_type', models.SmallIntegerField(default=0)),
                ('task_sketch', models.CharField(max_length=100)),
                ('task_bonus', models.IntegerField()),
                ('task_publishDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_phone', models.CharField(max_length=11)),
                ('user_password', models.CharField(max_length=20)),
                ('user_icon', models.BinaryField(default=None, null=True)),
                ('user_balance', models.IntegerField(default=100)),
                ('user_fillln', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
