# Generated by Django 2.2 on 2019-05-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xianyu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PickOrder',
            new_name='PickTask',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questionnaire_number',
            field=models.IntegerField(default=0),
        ),
    ]
