# Generated by Django 2.2 on 2019-05-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xianyu', '0002_auto_20190508_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answerSheet_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='questionnaire_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='task_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fan',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='following',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='picktask',
            name='task_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='picktask',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='task_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='task_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
