# Generated by Django 2.2 on 2019-05-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xianyu', '0003_auto_20190509_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_balance',
            field=models.IntegerField(default=0),
        ),
    ]
