# Generated by Django 2.2 on 2019-05-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xianyu', '0004_auto_20190510_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_balance',
            field=models.IntegerField(default=100),
        ),
    ]
