# Generated by Django 2.2 on 2019-05-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xianyu', '0005_auto_20190513_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_complishDate',
            field=models.DateTimeField(default=None),
        ),
    ]
