# Generated by Django 2.2 on 2019-05-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xianyu', '0006_auto_20190513_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_complishDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire_deadline',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
